#! /usr/bin/env python

# TODO: wow this sucks.
import gtk
import sys

# If postr is not installed we can run it from source
try:
    from postr import postr
except:
    sys.path.insert(0, ".")
    from src import postr

p = postr.Postr()
postr.Uploader(p).start()
p.window.show()
gtk.main()
